### ISSUE TITLE
Debug does not work in intellij ..

### ISSUE THREAD

**Issue by yingdi11** [grails-guides/grails-dynamic-multiple-datasources#2]
When I run the app in intellij , I can use post man to send request. However, when I debug the app , it appears the application is not started.

Debug log(not working):

"C:\Program Files\Java\jdk1.8.0_40\bin\java" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -Djline.WindowsTerminal.directConsole=false -Dgrails.full.stacktrace=true -Dfile.encoding=UTF-8 -classpath C:\Users\DiYing\AppData\Local\Temp\classpath1.jar org.grails.cli.GrailsCli run-app --debug-fork
|Running application...

Run log(working):

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Configuring Spring Security REST 2.0.0.M2...
... finished configuring Spring Security REST

Grails application running at http://localhost:8080 in environment: development

**Comment by yingdi11** [comment]
It is Jrebel mess things up. After disable JRebel, it is working fine!

**Comment by Oja95** [comment]
If JRebel was the root of the problem here, perhaps you could drop us an issue description to support@zeroturnaround.com and we'll look into fixing this use case.
